### ISSUE TITLE
https redirection not working

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Going to http://kubewarden.io doesn't redirect to https://kubewarden.io

### Expected Behavior

Automatic redirection takes place

**Comment by viccuad** [comment]
I think this may just be enabling `settings -> code and automation -> pages -> force https redirect`.
If not, I would try with: https://stackoverflow.com/questions/54817253/github-pages-https-www-redirect/58672792#58672792.

(I lack perms).

**Comment by flavio** [comment]
I've enabled and that's working. Thanks for figuring out the solution
