### ISSUE TITLE
Blog post about the env variable policy

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#134]
Write a blog post about the env variable policy

**Comment by jvanz** [comment]
I've moved this issue to blocked because I'm investigating why the examples are not working. Even if I use the same examples from the test cases.

**Comment by jvanz** [comment]
Moving to block until this [PR](https://github.com/kubewarden/environment-variable-policy/pull/9) is merged and released

**Comment by flavio** [comment]
@jvanz: This is going to be published on Mon 31 Oct.

Don't forget to update the publish date inside of the metadata ;)
