### ISSUE TITLE
Trademarks: transfer any trademark and logo mark assets over to the LF 

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#143]
See the agreement [here](https://github.com/cncf/foundation/tree/master/agreements)

**Comment by jvanz** [comment]
@kubewarden/kubewarden-developers I supose that SUSE legal department would like to take a look in the agreements. Isn't it? Who I can contact for that? Furthermore, Who can I contact to confirm the information necessary to add in the agreement?

**Comment by jvanz** [comment]
During the week planning meeting @flavio shared with me the person whom can help me with the information for the agreement. I've contact him and now I'm waiting his feedback.

**Comment by jvanz** [comment]
I'm talking with the legal team to move this forward.

**Comment by jvanz** [comment]
I've sent a draft of the agreement filled up for the legal team to review.

**Comment by jvanz** [comment]
I've pinged the legal team again asking for a feedback.

**Comment by jvanz** [comment]
During a call @flavio answered all the question from the legal team. They will work in the documents in the next weeks. Therefore, I'm moving this card back to the block column while we wait for their feedback.

**Comment by jvanz** [comment]
Reviewing the documents sent by the legal team.

**Comment by jvanz** [comment]
The documents seems to be fine. Waiting for another feedback from a SUSE team

**Comment by flavio** [comment]
The trademark transfer has been done 🥳
