### ISSUE TITLE
Website: Analytics transferred to projects@cncf.io

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#144]
### Acceptance criteria

Talk with Paul (Rancher).

**Comment by jvanz** [comment]
Moved to block until we get a feedback from Paul.

**Comment by jvanz** [comment]
I've asked the CNCF people to send the analytics tracking ID to configure our website.

**Comment by jvanz** [comment]
Waiting for CNCF people to send the analytics tracking ID

**Comment by jvanz** [comment]
Still waiting CNCF people

**Comment by jvanz** [comment]
I've scheduled a call with CNCF people to talk about this

**Comment by jvanz** [comment]
I just have a conversation with CNCF folks. They will create a new Google analytics for Kuberwarden and we will be added as "maintainers" of that project in case we can to customize dashboard and etc.

**Comment by chalin** [comment]
As I mention in the opening comment of #223, that PR updates the site ID for `www` only. You team will need to update it for all other subdomains. Adding the subtasks here for easier tracking:

- [ ] `www`- #223 
- [ ] `charts`
- [ ] `docs`

/cc @nate-double-u

**Comment by jvanz** [comment]
@kubewarden/kubewarden-developers do we need to add the Google analytics in the `charts.kubewarden.io` ? I think this is not necessary. Furthermore,  as far as I can see chart releaser has no  configuration to set this in the web page...

**Comment by flavio** [comment]
I don't think we have to enable that on the helm chart repo. I don't think this is doable either...

I think we can mark this issue as done. Thanks to everyone!
