### ISSUE TITLE
Shift kubewarden site deployment to Netlify

### ISSUE THREAD

**Issue by reveurguy** [kubewarden/kubewarden.io#161]
Shifting kubewarden deployment to netlify would allow us to access build previews for PR that would help make the PR review and feedback process faster and efficient.

**Comment by flavio** [comment]
Having a deployment preview would be really appreciated, however I don't think we have to move to netlify entirely. For example, our [documentation website](https://github.com/kubewarden/docs/) is hosted by GH pages, but the preview is done via netlify.

See [this PR](https://github.com/kubewarden/docs/pull/147) as a reference of what we would love to obtain.

**Comment by reveurguy** [comment]
I don't think that we can use netlify deploy previews if we have not hosted on Netlify ( according to my knowledge). I searched and couldn't find any way for that. 
One way i can think is to deploy the site on Netlify as well and link the repository to access deploy previews while still using github pages as the primary deploy tool.

**Comment by jvanz** [comment]
I think we can close this issue. We already use Netlify in our PRs.
