### ISSUE TITLE
Blogpost about 1.7.0 release

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden.io#189]
Small blogpost that lists the different changelogs, and teases on all the new features and fixes. Links to the new docs so people go read them.

**Comment by viccuad** [comment]
Possible contents:
Audit scanner, namespace labels propagator, UI fixes, run Kyverno policies, writing policies in plain WASI, 
On the policies side, support severity and category annotations as part of audit-scanner, add needed features to kwctl for compatibility, kwctl works with sha now, refactor of go policies to move away from easyjson.
On Helm charts, small bug fixes and exposed features via values.yml
Also, as byproducts, refactored GHA CIs and container build processes.

**Comment by flavio** [comment]
Moving to blocked, waiting for the actual release to be done
