### ISSUE TITLE
Enable analytics on the production server only

### ISSUE THREAD

**Issue by chalin** [kubewarden/kubewarden.io#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploy previews have analytics enabled, for example see https://deploy-preview-223--moonlit-trifle-c6359f.netlify.app/ for the `www` subdomain.

### Expected Behavior

Analytics should only be enabled in production.

### Environment

- Website

### Anything else?

- Related: #144

/cc @nate-double-u

**Comment by jvanz** [comment]
Reopening it. It's missing one PR to be merged
