### ISSUE TITLE
Blog post about 1.19.0 release

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#282]
Write a blog post about Kubewarden 1.19.0:

- [ ] Usual stream of bug fixes and dependency updates
- [ ] Fix to policy-server BOM and attestation
- [ ] Fixed issue with `slsactl`, but also explain how to use `slsactl` to verify KW stack
- [ ] Removal of post-install helm hooks
- [ ] Updated OTel CRDs from alpha v1 to beta v1. Mention which version of OTel we support
- [ ] Mention the cleanup/improvement work that has been done to our community repository. @agilgur5 is it fine if we mention you?

**Comment by agilgur5** [comment]
> @agilgur5 is it fine if we mention you?

Sure np, thanks for the shout out 🙂

**Comment by flavio** [comment]
Moving to blocked, everything is good to go. We will release 1.19 on 02 Mon Dec

**Comment by flavio** [comment]
@jvanz as usual, don't forget to update the date of the blog post :)
