### ISSUE TITLE
Top bar broken on mobile devices

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#30]
The navigation bar at the top of the page is broken when the website is visited on a small screen device.

This how it looks like on iphone 7

![image](https://user-images.githubusercontent.com/22728/134357210-8dcf21de-aa6b-4b85-910b-a4947984edcf.png)

**Comment by flavio** [comment]
@ncounter: maybe you can help us with that? :pray:

**Comment by ereslibre** [comment]
I think this is related to the theme, was reported some time ago: https://github.com/rancherlabs/projects-theme/issues/4

**Comment by kkaempf** [comment]
@ereslibre [your fix to assets/sass/main.scss](https://github.com/rancherlabs/projects-theme/issues/4#issue-863775483) is missing on kubewarden.io !? Maybe we should just add it there ?

**Comment by jvanz** [comment]
Fixed at #73. Closing.
