### ISSUE TITLE
Main website: add link to policy hub

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#4]
* We should have a direct link to `hub.kubewarden.io` inside of the top bar of the page.
* We should also have some contents on the main page talking about it.

**Comment by ereslibre** [comment]
We have to figure out what we want to say and where in the website, asked in https://github.com/kubewarden/kubewarden.io/issues/1

**Comment by ereslibre** [comment]
Closing, we can revisit.
