### ISSUE TITLE
Make access to blog from front page more prominent

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden.io#40]
Many visitors that make it to the root front page don't visit the blog. It could be that the contents on the main page are enough to grasp what Kubewarden is about and that it fullfills the needs of the visitors. It's also possible that the link to the blog is not super straightforward and not trivially discoverable.

Make the access to the blog more prominent. For example, adding a link and tiny summary of the last blog post on the front page. Or any other way that makes the blog more discoverable from the front page.

**Comment by viccuad** [comment]
With https://github.com/kubewarden/kubewarden.io/pull/79, a blog link is show in header (like https://sigstore.dev). Maybe that's enough for closing this card.
