### ISSUE TITLE
Maintainers file (Optional): ensure all our major repositories (kubewarden-controller, policy-server and kwctl) include this documentation

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#49]

**Comment by olblak** [comment]
I am not 100% what the maintainer file should be.
I bet on one CODEOWNER per repository where we would mention by default the team "kubewarden-developers"

**Comment by viccuad** [comment]
I agree with that.

**Comment by ereslibre** [comment]
>  I bet on one CODEOWNER per repository where we would mention by default the team "kubewarden-developers"

👍

**Comment by ereslibre** [comment]
This is done.
