### ISSUE TITLE
Define a code of Conduct

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#50]

**Comment by olblak** [comment]
GitHub provides two code of conducts template.

**Contributor Covenant**:
As GitHub says "recommended for projects of all size", .
https://www.contributor-covenant.org/version/2/0/code_of_conduct.html

**Citizen code of conduct
As GitHub says "suitable for large communities and events"

In both cases, we would need to provide an email address for reporting issues.

Should we use `info@kubewarden.io or a different one
Who would receive questions/complaints related to the code of conduct?

Personally, I would go with the contributor covenant

Once we have an agreement, I proceed forward by creating the file on https://github.com/kubewarden/.github so it applies to every git repository in the kubewarden organization.

**Comment by ereslibre** [comment]
There is also the CNCF Community Code of Conduct (https://kubernetes.io/community/code-of-conduct/#cncf-community-code-of-conduct-v1-0) that is the one adopted by Kubernetes.

This one is based on the Contributor Covenant but I didn't do a diff of what has been adapted for the CNCF Community Code of Conduct.

I think it might also be interesting to see if we want to adapt the CNCF one. I agree in making this available to all repos on the org by using `~/kubewarden/.github`.

**Comment by olblak** [comment]
The CNCF code of conduct is based on the "Contributor Covenant" but it is slightly different than the one generated from GitHub. My take on this is because the CNCF one was created +- 5 years before GitHub offers Code of conduct templates.

So to be closer to the CNCF one, I'll use the contributor covenant.
The last information needed is the email contact address

**Comment by olblak** [comment]
Now every repository in the Kubewarden organization has a link to the code of conduct as you can see in the screenshot 
![image](https://user-images.githubusercontent.com/2360224/151194488-61119669-caf6-4fa6-956f-501a95a981d8.png)
