### ISSUE TITLE
Guidelines/help for project contributors: ensure all our major repositories (kubewarden-controller, policy-server and kwctl) include this documentation

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#52]
* [x] Add "Adopters" file used by CLO monitor
* [x] Add "contributing"

**Comment by olblak** [comment]
Add "Adopters" file used by CLO monitor
Add "contributing"

**Comment by flavio** [comment]
@olblak Thanks, I've added your comment to the main body of the issue as a checklist

**Comment by flavio** [comment]
Closing, this has been implemented
