### ISSUE TITLE
Blog: logos at the bottom are broken

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden.io#57]
There is something off in the blog template: https://www.kubewarden.io/blog/.

![image](https://user-images.githubusercontent.com/8706/152116368-8d80bf29-fd2e-4f49-a853-35735529b4ec.png)

**Comment by kkaempf** [comment]
It's a browser or proxy issue. Works for me on Firefox.

**Comment by ereslibre** [comment]
> It's a browser or proxy issue. Works for me on Firefox.

I can reproduce. Image sources point to URL's that 404 like https://www.kubewarden.io/blog/images/icon-k3s.svg.

**Comment by jvanz** [comment]
I can also reproduce on Firefox without proxy.
