### ISSUE TITLE
Missing blog link in the kubewarden.io

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden.io#76]
At the time of this writing, there is no link to the blog in the kubewarden.io page. We should add it there.

**Comment by viccuad** [comment]
In addition, there's a string "Main menu" appearing in https://kubewarden.io/blog, which seems to come from:

https://github.com/kubewarden/kubewarden.io/blob/0f70711e055aef24c834ded7dd7d6bd88a48e467/layouts/partials/header.html#L12
